# Generated by Django 5.2.4 on 2025-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculatorapp', '0002_emailconfirmationtoken_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
